apiVersion: v2
name: simpl-participant
description: A Helm chart for Kubernetes

type: application

version: "0.7.0-SNAPSHOT"

appVersion: "0.7.0-SNAPSHOT"

dependencies:
  - name: redis
    version: "19.6.0"
    repository: https://charts.bitnami.com/bitnami
  - name: postgresql
    version: "15.2.5"
    repository: https://charts.bitnami.com/bitnami
  - name: keycloak
    repository: https://charts.bitnami.com/bitnami
    version: "22.2.5"
  - name: simpl-cloud-gateway
    repository: https://code.europa.eu/api/v4/projects/772/packages/helm/stable
    version: "0.7.0-SNAPSHOT.242.68415818"
  - name: users-roles
    version: "0.7.0-SNAPSHOT.766.cf371aaa"
    repository: https://code.europa.eu/api/v4/projects/771/packages/helm/stable
  - name: authentication-provider
    version: "0.7.0-SNAPSHOT.57.e77c5c7b"
    repository: https://code.europa.eu/api/v4/projects/939/packages/helm/stable
  - name: simpl-fe
    version: "0.7.0-SNAPSHOT.821.e098f635"
    repository: https://code.europa.eu/api/v4/projects/769/packages/helm/stable

