postgresql:
  primary:
    resources:
      requests:
        memory: 256Mi
        cpu: 100m
      limits:
        memory: 1Gi
        cpu: 1

users-roles:
  authorityHostT2: t2.iaa-dsautomation-authority.dev.simpl-europe.eu #the authority host tier 2

authentication-provider:
  appConfig:
    client:
      authority:
        url: https://t2.iaa-dsautomation-authority.dev.simpl-europe.eu

  resources:
    limits:
      memory: 1Gi
      cpu: 1
  vaultConfig:
    vault:
      uri : [NOT_SET]

tier2-gateway:
  authorityUrlT1: "https://t1.iaa-dsautomation-authority.dev.simpl-europe.eu"

simpl-cli:
  initParticipant:
    enabled: false
    authorityHostT1: t1.iaa-dsautomation-authority.dev.simpl-europe.eu

tier1-gateway:
  appConfig:
    external-routes:
      public-urls:
        - path: /internal/**
        - path: /postgrest/**
        - method: GET
          path: /authApi/v1/agent/ephemeralProof
        - method: GET
          path: /authApi/tier1/v2/ephemeralProof
        - method: GET
          path: /authApi/tier1/v2/participant
        - method: GET
          path: /authApi/tier1/v2/participant/identityAttributes
        - method: GET
          path: /authApi/tier1/v2/participants/{participantId}
        - method: GET
          path: /authApi/tier1/v2/participants/{participantId}/identityAttributes
        - method: GET
          path: /authApi/tier1/v2/credentials/{credentialId}/participant
      spring-route-definitions:
        - id: postgrest-authenticationprovider
          uri: http://postgrest-authenticationprovider.{{ .Release.Namespace }}.svc.cluster.local:3000
          predicates:
            - Path=/postgrest/authenticationprovider/**
          filters:
            - StripPrefix=2
        - id: postgrest-usersroles
          uri: http://postgrest-usersroles.{{ .Release.Namespace }}.svc.cluster.local:3000
          predicates:
            - Path=/postgrest/usersroles/**
          filters:
            - StripPrefix=2
        - id: cleanup-users-with-CLI
          uri: ${users-roles.url}
          predicates:
            - Path=
              /cli/userApi/v1/users,
              /cli/userApi/v1/users/*,
              /cli/userApi/v1/roles,
              /cli/userApi/v1/roles/*,
          filters:
            - StripPrefix=2
            - name: ClientCredentialsFilterFactory
              args:
                cli: cli-role
        - id: authenticationprovider-internal
          uri: ${authentication-provider.url}
          predicates:
            - Path=/internal/authApi/**
          filters:
            - StripPrefix=2
postgrest:
  enabled: true
  databases: 
    - name: authenticationprovider
      uri: postgres://authenticationprovider:authenticationprovider@postgresql.{{ .Release.Namespace }}.svc.cluster.local:5432/authenticationprovider
      anonRole: authenticationprovider
      dbPool: 1
    - name: usersroles
      uri: postgres://usersroles:usersroles@postgresql.{{ .Release.Namespace }}.svc.cluster.local:5432/usersroles
      anonRole: usersroles
      dbPool: 1
