global:
  cors:
    allowOrigin: https://participant01-be.dev.simpl-europe.eu,https://participant01-fe.dev.simpl-europe.eu,http://localhost:4202,http://localhost:3000
  hostBe: participant01-be.dev.simpl-europe.eu
  hostFe: participant01-fe.dev.simpl-europe.eu # not needed
  authorityUrl: https://authority.be.dev.simpl-europe.eu
  hostTls: tls-participant01.dev.simpl-europe.eu
  ingress:
    issuer: dev-prod
  profile: participant

microservices:
  keycloakUrl: http://keycloak.iaa-01.svc.cluster.local
  usersRolesUrl: http://users-roles.iaa-01.svc.cluster.local:8080

springRoutes: 
  - id: keycloak
    uri: ${keycloak.url}
    predicates:
      - Path=/auth/**
    filters:
      - StripPrefix=1
  - id: users-roles
    uri: ${users-roles.url}
    predicates:
      - Path=/*/user-api/**
    filters:
      - StripPrefix=2

swaggerUrls:
  - url: /public/user-api/v3/api-docs
    name: Users & Roles Service

routes:
  publicUrls:
    - method: GET
      path: "/swagger-ui.html"
    - method: GET
      path: "/swagger-ui/**"
    - method: GET
      path: "/v3/api-docs/**"
    - method: GET
      path: "/actuator/**"

  rbac:
    - path: "private/user-api/agent/identity-attributes"
      method: GET
      roles:
        - T1UAR_M
    - path: "private/user-api/agent/identity-attributes/*"
      method: GET
      roles:
        - T1UAR_M
    - path: "private/user-api/identity-attribute/search"
      method: GET
      roles:
        - T1UAR_M
    - path: "private/user-api/role/*"
      method: GET
      roles:
        - T1UAR_M
    - path: "private/user-api/role"
      method: PUT
      roles:
        - T1UAR_M
    - path: "private/user-api/role/*/identity-attributes"
      method: POST
      roles:
        - T1UAR_M
    - path: "private/user-api/role/delete-attribute"
      method: DELETE
      roles:
        - T1UAR_M
    - path: "private/user-api/role/*"
      method: DELETE
      roles:
        - T1UAR_M
    - path: "private/user-api/role/search"
      method: GET
      roles:
        - T1UAR_M
    - path: "private/user-api/role/*/duplicate-identity-attribute"
      method: POST
      roles:
        - T1UAR_M
    - path: "private/user-api/user/as-t1user"
      method: POST
      roles:
        - T1UAR_M
    - path: "private/user-api/user/*"
      method: GET
      roles:
        - T1UAR_M
    - path: "private/user-api/user/*"
      method: PUT
      roles:
        - T1UAR_M
    - path: "private/user-api/user/*"
      method: DELETE
      roles:
        - T1UAR_M