services:
  redpanda:
    image: redpandadata/redpanda:latest
    container_name: redpanda
    command:
      - redpanda
      - start
      - --overprovisioned
      - --smp=1
      - --memory=256M
      - --reserve-memory=0M
      - --node-id=0
      - --check=false
      - --kafka-addr=internal://0.0.0.0:19092,external://0.0.0.0:9092
      - --advertise-kafka-addr=internal://redpanda:19092,external://localhost:9092
    ports:
      - "9092:9092"
      - "9644:9644" # Admin API
    restart: unless-stopped
    mem_limit: 256m

  console:
    image: redpandadata/console:latest
    container_name: redpanda-console
    environment:
      KAFKA_BROKERS: redpanda:19092
    ports:
      - "8888:8080"
    depends_on:
      - redpanda
    restart: unless-stopped
