#!/bin/bash
set -e

REPACKAGE="true"
SPOTLESS_CMD="spotless:apply";

# Flag file to trigger init build
FLAG_FILE=".init.flag";

[ ! -f "$FLAG_FILE" ] && INIT="true"


while true; do
	case $1 in
		--init)
        INIT="true"
		shift
		;;
		--no-init)
        INIT="false"
		shift
		;;
		--spotless)
        SPOTLESS_CMD="spotless:apply"
		shift
		;;
		--no-spotless)
        SPOTLESS_CMD=""
		shift
		;;
		--repackage)
        REPACKAGE="true"
		shift
		;;
		--no-repackage)
        REPACKAGE="false"
		shift
		;;
		--nt)
		# Skip test
        NO_TESTS="true"
		shift
		;;
		--)
		shift
		break;
		;;
		*)
		break;
		;;
	esac
done;

if [[ $REPACKAGE == "true" ]]; then
	REPACKAGE_COMMAND=""
else
	REPACKAGE_COMMAND="-Dspring-boot.repackage.skip"
fi

if [[ $NO_TESTS == "true" ]]; then
	MVN_SKIP_TEST="-Dmaven.test.skip"
else
	MVN_SKIP_TEST=""
fi


# Maven build with default parameters
build='mvn -fae '$SPOTLESS_CMD' '$MVN_SKIP_TEST' clean install '$REPACKAGE_COMMAND' -Dsurefire.failIfNoSpecifiedTests=false -am'

if [[ $INIT == "true" ]]; then
    $build -N -f simpl-repo/common;
    touch "$FLAG_FILE";
fi

$build "$@"
