#!/bin/bash

build='mvn -fae clean install -Dspring-boot.repackage.skip -Dsurefire.failIfNoSpecifiedTests=false -am'

	case $1 in
		--init)
        $build -N -f common
		shift
		;;
	esac


$build "$@"
