services:

  port-forward:
    image: alpine/socat
    networks:
      - "simpl-network"
    ports:
      - "30888:30888"
      - "30443:30443"
      - "30432:30432"
      - "30379:30379"
      - "30205:30205"
      - "30201:30201"
      - "30200:30200"
      - "30105:30105"
      - "30104:30104"
      - "30103:30103"
      - "30102:30102"
      - "30101:30101"
      - "30090:30090"
    entrypoint: /bin/sh
    command: |
      -c '
      log() { echo "[`date "+%Y-%m-%d %H:%M:%S"`] [socat-forward] $1"; }
      portf() { log "Starting port-forward $1"; socat -v -d tcp-listen:$1,fork,reuseaddr tcp:simpl-control-plane:$1 2>&1 | cut -c -100; }
      portf 30090 &
      portf 30101 &
      portf 30102 &
      portf 30103 &
      portf 30104 &
      portf 30105 &
      portf 30200 &
      portf 30201 &
      portf 30205 &
      portf 30379 &
      portf 30432 &
      portf 30443 &
      portf 30888 &
      log "Socat port fotward running"
      wait -n
      log "A connection was interrupted. Socat close"
      kill $(jobs -p)
      '
    restart: unless-stopped

networks:
  simpl-network:
    external: true
