{{- $postgrest := .Values.postgrest | default dict }}
{{- if $postgrest.enabled | default false }}
{{- range $postgrest.databases | default list }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgrest-{{ .name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgrest-{{ .name }}
  template:
    metadata:
      labels:
        app: postgrest-{{ .name }}
    spec:
      containers:
        - name: postgrest
          image: postgrest/postgrest:latest
          env:
            - name: PGRST_DB_URI
              value: {{ tpl .uri $ | quote  }}
            - name: PGRST_DB_ANON_ROLE
              value: {{ .anonRole | quote  }}
            {{- if .jwtSecret }}
            - name: PGRST_JWT_SECRET
              value: {{ .jwtSecret | quote  }}
            {{- end }}
            - name: PGRST_DB_POOL
              value: {{ .dbPool | quote  }}
          ports:
            - containerPort: 3000
---
{{- end }}
{{- end }}
