image: 
  tag: 0.6.6
global:
  hostBe: participant01-be.dev.simpl-europe.eu
  hostTls: tls.authority.dev.simpl-europe.eu # authority
  profile: participant
  keystore:
    password: "keystore-generated-password"

db:
  url: "jdbc:postgresql://postgresql.iaa-01.svc.cluster.local:5432/usersroles"
  username: "usersroles"
  password: "usersroles"

redis:
  host: "redis-master.iaa-01.svc.cluster.local"
  port: "6379"
  username: "default"
  password: "admin" # update this

keycloak:
  master:
    user: "user"
    password: "admin"