hostname: &hostname ejbca-community-helm.iaa.svc.cluster.local
fullnameOverride: ejbca-community-helm
ejbca:
  env:
    HTTPSERVER_HOSTNAME: *hostname
    TLS_SETUP_ENABLED: "true"
    DATABASE_JDBC_URL: jdbc:postgresql://postgresql.iaa.svc.cluster.local:5432/ejbca
    DATABASE_USER: "ejbca"
    DATABASE_PASSWORD: "ejbca2123"
nginx:
  host: *hostname
