apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-console
spec:
  replicas: {{ .Values.console.replicas }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}-console
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}-console
    spec:
      containers:
        - name: console
          image: {{ .Values.console.image }}
          env:
            - name: KAFKA_BROKERS
              value: "redpanda.{{ .Release.Namespace }}.svc.cluster.local:{{ .Values.redpanda.service.ports.internal}}"
          ports:
            - containerPort: {{ .Values.console.service.port }}
          resources:
{{ toYaml .Values.redpanda.resources | indent 12 }}
