global:
  cors:
    allowOrigin: https://t1.iaads-participant-01.dev.simpl-europe.eu,https://fe.iaads-participant-01.dev.simpl-europe.eu,http://localhost:4202,http://localhost:3000
  hostBe: t1.iaads-participant-01.dev.simpl-europe.eu
  hostTls: t2.iaads-authority-01.dev.simpl-europe.eu # authority
  ingress:
    issuer: dev-prod
  profile: participant

postgresql:
  fullnameOverride: postgresql
  primary:
    persistence:
      size: 1Gi
    initdb:
      scripts:
        init.sql: |
          CREATE USER keycloak WITH PASSWORD 'keycloak' CREATEDB;
          CREATE DATABASE keycloak OWNER keycloak;
          CREATE USER usersroles WITH PASSWORD 'usersroles' CREATEDB;
          CREATE DATABASE usersroles OWNER usersroles;
          CREATE USER authenticationprovider WITH PASSWORD 'authenticationprovider' CREATEDB;
          CREATE DATABASE authenticationprovider OWNER authenticationprovider;
redis:
  fullnameOverride: redis
  replica:
    replicaCount: 1
    persistence:
      size: 1Gi
  master:
    persistence:
      size: 1Gi
  auth:
    password: "admin"

keycloak:
  fullnameOverride: keycloak
  apiUrl: "https://t1.iaads-participant-01.dev.simpl-europe.eu"
  extraEnvVars:
    - name: KC_HOSTNAME_ADMIN
      value: "https://t1.iaads-participant-01.dev.simpl-europe.eu/auth"
    - name: KC_HOSTNAME
      value: "https://t1.iaads-participant-01.dev.simpl-europe.eu/auth"
    - name: USERS_ROLES_BASE_URL
      value: "http://users-roles.iaads-participant-01.svc.cluster.local:8080"
    - name: KEYCLOAK_BASE_URL
      value: "https://t1.iaads-participant-01.dev.simpl-europe.eu/auth"
    - name: REALM
      value: "participant"
    - name: KEYCLOAK_EXTRA_ARGS
      value: --import-realm

  auth:
    adminPassword: "admin"

  postgresql:
    enabled: false

  externalDatabase:
    host: "postgresql.iaads-participant-01.svc.cluster.local"
    port: 5432
    user: keycloak
    database: keycloak
    password: "keycloak"
    existingSecret: ""
    existingSecretHostKey: ""
    existingSecretPortKey: ""
    existingSecretUserKey: ""
    existingSecretDatabaseKey: ""
    existingSecretPasswordKey: ""
    annotations: {}

  extraVolumes:
    - name: spi-volume
      emptyDir: {}
    - name: realm-volume
      emptyDir: {}

  extraVolumeMounts:
    - name: spi-volume
      mountPath: /opt/bitnami/keycloak/providers/keycloak-authenticator.jar
      subPath: keycloak-authenticator.jar
    - name: realm-volume
      mountPath: /opt/bitnami/keycloak/data/import/realm.json
      subPath: realm.json

  initContainers:
    - name: init-spi
      image: curlimages/curl
      command: ["/bin/sh", "-c"]
      env:
        - name: ARTIFACT
          value: keycloak-authenticator
        - name: URL
          value: https://code.europa.eu/api/v4/projects/915/packages/maven/com/aruba/simpl/keycloak-authenticator/0.7.0/keycloak-authenticator-0.7.0.jar
      args:
        - |
          curl -o /custom-spi/${ARTIFACT}.jar ${URL};
      volumeMounts:
        - name: spi-volume
          mountPath: /custom-spi

    - name: import-realm
      image: curlimages/curl
      command: ["/bin/sh", "-c"]
      env:
        - name: REALM_NAME
          value: realm
        - name: URL
          value: https://code.europa.eu/simpl/simpl-open/development/iaa/charts/-/raw/develop/samples/keycloak-realms/0.6/participant-realm-export.json?ref_type=heads&inline=false
      args:
        - |
          curl -o /config/${REALM_NAME}.json ${URL};
      volumeMounts:
        - name: realm-volume
          mountPath: /config


simpl-cloud-gateway:
  keycloakUrl: http://keycloak.iaads-participant-01.svc.cluster.local
  usersRolesUrl: http://users-roles.iaads-participant-01.svc.cluster.local:8080
  authenticationProviderUrl: http://authentication-provider.iaads-participant-01.svc.cluster.local:8080

  # Spring Cloud Gateway Routes Participant
  appConfig:
    spring:
      cloud:
        gateway:
          routes: 
            - id: keycloak
              uri: ${keycloak.url}
              predicates:
                - Path=/auth/**
              filters:
                - StripPrefix=1
            - id: users-roles
              uri: ${users-roles.url}
              predicates:
                - Path=/*/user-api/**
              filters:
                - StripPrefix=2
            - id: authentication-provider
              uri: ${authentication-provider.url}
              predicates:
                - Path=/*/auth-api/**
              filters:
                - StripPrefix=2
    springdoc:
      swagger-ui:
        urls:
          - url: /public/user-api/v3/api-docs
            name: Users & Roles Service
          - url: /public/auth-api/v3/api-docs
            name: Authentication Provider Service

    routes:
      public-urls:
        - method: GET
          path: "/swagger-ui.html"
        - method: GET
          path: "/swagger-ui/**"
        - method: GET
          path: "/v3/api-docs/**"
        - method: GET
          path: "/actuator/**"

      denied-urls:
        - method: GET
          path: "*/auth-api/keypair"

      rbac:
        - path: "private/user-api/agent/identity-attributes"
          method: GET
          roles:
            - T1UAR_M
        - path: "private/user-api/agent/identity-attributes/*"
          method: GET
          roles:
            - T1UAR_M
        - path: "private/user-api/identity-attribute/search"
          method: GET
          roles:
            - T1UAR_M
        - path: "private/user-api/role/*"
          method: GET
          roles:
            - T1UAR_M
        - path: "private/user-api/role"
          method: PUT
          roles:
            - T1UAR_M
        - path: "private/user-api/role/*/identity-attributes"
          method: POST
          roles:
            - T1UAR_M
        - path: "private/user-api/role/delete-attribute"
          method: DELETE
          roles:
            - T1UAR_M
        - path: "private/user-api/role/*"
          method: DELETE
          roles:
            - T1UAR_M
        - path: "private/user-api/role/search"
          method: GET
          roles:
            - T1UAR_M
        - path: "private/user-api/role/*/duplicate-identity-attribute"
          method: POST
          roles:
            - T1UAR_M
        - path: "private/user-api/user/as-t1user"
          method: POST
          roles:
            - T1UAR_M
        - path: "private/user-api/user/**"
          method: GET
          roles:
            - T1UAR_M
        - path: "private/user-api/user/**"
          method: PUT
          roles:
            - T1UAR_M
        - path: "private/user-api/user/*"
          method: DELETE
          roles:
            - T1UAR_M
        - method: POST
          path: "private/auth-api/keypair/import"
          roles:
            - ONBOARDER_M 
        - path: "private/auth-api/keypair/**"
          roles:
            - ONBOARDER_M 
        - method: POST
          path: "private/auth-api/csr/generate"
          roles:
            - ONBOARDER_M

simpl-fe:
  hostFe: fe.iaads-participant-01.dev.simpl-europe.eu
  cors:
    allowOrigin: https://t1.iaads-participant-01.dev.simpl-europe.eu,https://fe.iaads-participant-01.dev.simpl-europe.eu,http://localhost:4202,http://localhost:4203,http://localhost:3000
  ingress:
    issuer: dev-prod

  env:
  - name: API_URL
    value: "https://t1.iaads-participant-01.dev.simpl-europe.eu"
  - name: KEYCLOAK_URL
    value: "https://t1.iaads-participant-01.dev.simpl-europe.eu/auth"
  - name: KEYCLOAK_REALM
    value: "participant"
  - name: KEYCLOAK_CLIENT_ID
    value: "frontend-cli"

  microfrontends:
  - name: usersroles
    application: usersandroles
    path: "/users-roles"
  - name: participant
    application: participant-utility
    path: "/participant-utility"

users-roles:
  db:
    url: "jdbc:postgresql://postgresql.iaads-participant-01.svc.cluster.local:5432/usersroles"
    username: "usersroles"
    password: "usersroles"

  redis:
    host: "redis-master.iaads-participant-01.svc.cluster.local"
    port: "6379"
    username: "default"
    password: "admin" # update this

  keycloak:
    master:
      user: "user"
      password: "admin"
  
  microservices:
    authenticationProviderUrl: http://authentication-provider.iaads-participant-01.svc.cluster.local:8080

tls-gateway:
  keypair:
    algorithm: EC

  microservices:
    usersRolesUrl: http://users-roles.iaads-participant-01.svc.cluster.local:8080 
    keycloakUrl: http://keycloak.iaads-participant-01.svc.cluster.local
    authenticationProviderUrl: http://authentication-provider.iaads-participant-01.svc.cluster.local:8080

  redis:
    host: "redis-master.iaads-participant-01.svc.cluster.local"
    port: "6379"
    username: "default"
    password: "admin"

  authorityUrlT1: "https://t1.iaads-authority-01.dev.simpl-europe.eu"
  hostT2: "t2.iaads-participant-01.dev.simpl-europe.eu"
  appConfig:
    spring:
      cloud:
        gateway:
          routes:
            - id: users-roles
              uri: ${users-roles.url}
              predicates:
                - Path=/user-api/mtls/**
              filters:
                - StripPrefix=1

    routes:
      public-urls:
        - method: GET
          path: "/actuator/**"
      abac:
        - method: POST
          path: "/user-api/mtls/ephemeral-proof"
          disable-ephemeral-proof-check: true

authentication-provider:
  db:
    url: "jdbc:postgresql://postgresql.iaads-participant-01.svc.cluster.local:5432/authenticationprovider"
    username: "authenticationprovider"
    password: "authenticationprovider"
    cipherSecret: "authenticationprovider-db-cipher-secret" # name of the secret key that will be generated used to encrypt keys  

  keypair:
    signatureAlgorithm: "SHA256withECDSA"
    algorithm: "ECDSA"
    keyLength: 256

  microservices:
    usersRolesUrl: http://users-roles.iaads-participant-01.svc.cluster.local:8080

  simpl:
    certificate:
      san: t2.iaads-participant-01.dev.simpl-europe.eu