events {}
http {
  server {
    listen 4100;
    location /participant-utility/ {
        proxy_pass http://fe-authentication-provider-authority:3000/;
    }
    location /identity-provider/ {
        proxy_pass http://fe-identity-provider-authority:3000/;
    }
    location /onboarding/ {
        proxy_pass http://fe-onboarding-authority:3000/;
    }
    location /sap/ {
        proxy_pass http://fe-security-attribute-provider-authority:3000/;
    }
    location /users-roles/ {
        proxy_pass http://fe-users-and-roles-authority:3000/;
    }
  }

  server {
    listen 4200;
    location /participant-utility/ {
        proxy_pass http://fe-authentication-provider-participant:3000/;
    }
    location /users-roles/ {
        proxy_pass http://fe-users-and-roles-participant:3000/;
    }
  }
}
