#!/usr/bin/env bash

set -e

export SPRING_DATASOURCE_URL=${MICRO_ONBOARDING_DB_URL}
export SPRING_DATASOURCE_USERNAME=${MICRO_ONBOARDING_DB_USERNAME}
export SPRING_DATASOURCE_PASSWORD=${MICRO_ONBOARDING_DB_PASSWORD}

mvnd -f simpl-repo/onboarding/ -Dmaven.test.skip spring-boot:run -Dspring-boot.run.profiles="${MICRO_PROFILES}" "$@"
