#!/usr/bin/env bash

set -e

export GATEWAY_URL="${MICRO_TIER1_GATEWAY_URL}"
export KEYCLOAK_APP_REALM="${MICRO_TIER1_REALM}"

mvnd -f simpl-repo/simpl-cloud-gateway/ -Dmaven.test.skip spring-boot:run -Dspring-boot.run.profiles="${MICRO_PROFILES}" "$@"
