CREATE USER ejbca WITH PASSWORD 'ejbca' CREATEDB;
CREATE DATABASE authority_ejbca OWNER ejbca;
-- CREATE USER ejbca WITH PASSWORD 'ejbca2123' CREATEDB;
-- CREATE DATABASE ejbca OWNER ejbca;
CREATE USER keycloak WITH PASSWORD 'keycloak' CREATEDB;
CREATE DATABASE keycloak OWNER keycloak;
CREATE USER authority_ejbca WITH PASSWORD 'authority_ejbca' CREATEDB;
CREATE DATABASE authority_ejbca OWNER authority_ejbca;
CREATE USER authority_usersroles WITH PASSWORD 'authority_usersroles' CREATEDB;
CREATE DATABASE authority_usersroles OWNER authority_usersroles;
CREATE USER authority_securityattributesprovider WITH PASSWORD 'authority_securityattributesprovider' CREATEDB;
CREATE DATABASE authority_securityattributesprovider OWNER authority_securityattributesprovider;
CREATE USER authority_identityprovider WITH PASSWORD 'authority_identityprovider' CREATEDB;
CREATE DATABASE authority_identityprovider OWNER authority_identityprovider;
CREATE USER authority_onboarding WITH PASSWORD 'authority_onboarding' CREATEDB;
CREATE DATABASE authority_onboarding OWNER authority_onboarding;
CREATE USER authority_authenticationprovider WITH PASSWORD 'authority_authenticationprovider' CREATEDB;
CREATE DATABASE authority_authenticationprovider OWNER authority_authenticationprovider;
CREATE USER consumer_usersroles WITH PASSWORD 'consumer_usersroles' CREATEDB;
CREATE DATABASE consumer_usersroles OWNER consumer_usersroles;
CREATE USER consumer_authenticationprovider WITH PASSWORD 'consumer_authenticationprovider' CREATEDB;
CREATE DATABASE consumer_authenticationprovider OWNER consumer_authenticationprovider;
