postgresql:
  image:
    repository: bitnamilegacy/postgresql
  security:
    allowInsecureImages: true
  architecture: standalone
  auth:
    postgresPassword: postgres
  primary:
    resources:
      requests:
        memory: 256Mi
        cpu: 50m
      limits:
        memory: 512Mi
        cpu: 200m
    persistence:
      size: 1Gi
    initdb:
      scriptsConfigMap: postgresql-init-configmap
      scripts:
        restore-ejbca.sh: | #!/bin/bash set -e
          echo "Restoring dump into ejbca..."
          export PGPASSWORD="postgres"
          #pg_restore -j 1 -U postgres -d authority_ejbca /ejbca-dump/ejbca.sql
          psql -U postgres -d authority_ejbca -f /ejbca-dump/ejbca.sql
    extraVolumes:
      - name: ejbca-dump
        configMap:
          name: ejbca-dump
    extraVolumeMounts:
      - name: ejbca-dump
        mountPath: /ejbca-dump

global:
  initDatabases:
    - name: authority_ejbca
      user: ejbca
      password: ejbca
      postgrest:
        enabled: false
    - name: authority_usersroles
      user: authority_usersroles
      password: authority_usersroles
      postgrest:
        enabled: true
        nodePort: 30101
        anonRole: postgres
    - name: authority_securityattributesprovider
      user: authority_securityattributesprovider
      password: authority_securityattributesprovider
      postgrest:
        enabled: true
        nodePort: 30102
        anonRole: postgres
    - name: authority_identityprovider
      user: authority_identityprovider
      password: authority_identityprovider
      postgrest:
        enabled: true
        nodePort: 30103
        anonRole: postgres
    - name: authority_onboarding
      user: authority_onboarding
      password: authority_onboarding
      postgrest:
        enabled: true
        nodePort: 30104
        anonRole: postgres
    - name: authority_authenticationprovider
      user: authority_authenticationprovider
      password: authority_authenticationprovider
      postgrest:
        enabled: true
        nodePort: 30105
        anonRole: postgres
    - name: consumer_usersroles
      user: consumer_usersroles
      password: consumer_usersroles
      postgrest:
        enabled: true
        nodePort: 30201
        anonRole: postgres
    - name: dataprovider_usersroles
      user: dataprovider_usersroles
      password: dataprovider_usersroles
      postgrest:
        enabled: true
        nodePort: 30301
        anonRole: postgres
    - name: consumer_authenticationprovider
      user: consumer_authenticationprovider
      password: consumer_authenticationprovider
      postgrest:
        enabled: true
        nodePort: 30205
        anonRole: postgres
    - name: dataprovider_authenticationprovider
      user: dataprovider_authenticationprovider
      password: dataprovider_authenticationprovider
      postgrest:
        enabled: true
        nodePort: 30305
        anonRole: postgres
    - name: keycloak
      user: keycloak
      password: keycloak
      postgrest:
        enabled: false
    - name: authority_consentmanagement
      user: authority_consentmanagement
      password: authority_consentmanagement
      postgrest:
        enabled: true
        nodePort: 30107
        anonRole: postgres
    - name: consumer_consentmanagement
      user: consumer_consentmanagement
      password: consumer_consentmanagement
      postgrest:
        enabled: true
        nodePort: 30207
        anonRole: postgres
    - name: dataprovider_consentmanagement
      user: dataprovider_consentmanagement
      password: dataprovider_consentmanagement
      postgrest:
        enabled: true
        nodePort: 30307
        anonRole: postgres

ejbca:
  hostname: &ejbca-hostname simpl-control-plane
  fullnameOverride: ejbca-community-helm
  serviceAccount:
    name: ejbca-init-sa
  image:
    tag: 8.2.0.1
  resources:
    requests:
      cpu: 250m
      memory: 500Mi
  ejbca:
    useEphemeralH2Database: false
    env:
      LOG_LEVEL_APP: DEBUG
      LOG_LEVEL_SERVER: DEBUG
      LOG_LEVEL_SERVER_SUBSYSTEMS: DEBUG
      HTTPSERVER_HOSTNAME: *ejbca-hostname
      TLS_SETUP_ENABLED: "true"
      DATABASE_JDBC_URL: &ejbca-db-url jdbc:postgresql://local-authority-postgresql.local-authority.svc.cluster.local:5432/authority_ejbca
      DATABASE_USER: &ejbca-db-user "ejbca"
      DATABASE_PASSWORD: &ejbca-db-password "ejbca"
  initContainers:
  - name: ejbca-init
    image: code.europa.eu:4567/simpl/simpl-open/development/iaa/ejbca-preconfig:1.0.2
    imagePullPolicy: IfNotPresent
    securityContext: {}
    env:
    - name: HTTPSERVER_HOSTNAME
      value: *ejbca-hostname
    - name: MANAGEMENT_END_ENTITY_USERNAME
      value: SuperAdmin
    - name: MANAGEMENT_END_ENTITY_PASSWORD
      value: 123-stella
    - name: DATABASE_JDBC_URL
      value: *ejbca-db-url
    - name: DATABASE_USER
      value: *ejbca-db-user
    - name: DATABASE_PASSWORD
      value: *ejbca-db-password
    - name: T1_GATEWAY
      value: tier1-gateway-authority:8100 # TODO configure also http instead of https (now manual config is required)
    - name: NAMESPACE
      value: local-authority
    command:
    - "./entrypoint.sh"
  

  nginx:
    host: *ejbca-hostname
  # The following allows to not use a NodePort and have multiple istances of EJBCA on the same cluster
  services:
    directHttp:
      type: ClusterIP

keycloak:
  image:
    repository: keycloak/keycloak
    tag: 26.4
  global:
    security:
      allowInsecureImages: true

  defaultInitContainers:
    prepareWriteDirs:
      enabled: false
  args:
    - start
    - --import-realm
    - --verbose
    - --proxy-headers
    - xforwarded
  containerSecurityContext:
    runAsUser: 1000
    runAsNonRoot: true
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: false
  requests:
    cpu: 30m
    memory: 192Mi
  limits:
    cpu: 300m
    memory: 384Mi
  apiUrl: "http://localhost:8100"
  extraEnvVars:
    - name: DEBUG
      value: 'true'
    - name: DEBUG_SUSPEND
      value: 'n'
    - name: DEBUG_PORT
      value: '*:5005'
    - name: KC_HOSTNAME_ADMIN
      value: "http://localhost:8100/auth"
    - name: KC_HOSTNAME
      value: "http://localhost:8100/auth"


    - name: USERS_ROLES_URLS_MAP
      value: |-
        {
          "authority": "http://host.docker.internal:8101/tier1/v2",
          "consumer": "http://host.docker.internal:8201/tier1/v2"
        }
    - name: AUTHENTICATION_PROVIDER_URLS_MAP
      value: |-
        {
          "authority": "http://host.docker.internal:8105/tier1/v2",
          "consumer": "http://host.docker.internal:8205/tier1/v2"
        }

    - name: KEYCLOAK_BASE_URL
      value: "http://localhost:8100/auth"
    - name: KEYCLOAK_EXTRA_ARGS
      value: --import-realm
    - name: KC_DB
      value: "postgres"
    - name: KC_DB_URL_HOST
      value: "local-authority-postgresql.local-authority.svc.cluster.local"
    - name: KC_DB_URL_PORT
      value: "5432"
    - name: KC_DB_URL_DATABASE
      value: "keycloak"
    - name: KC_DB_USERNAME
      value: "keycloak"
    - name: KC_DB_PASSWORD
      value: "keycloak"
    - name: KEYCLOAK_ADMIN
      value: "admin"
    - name: KEYCLOAK_ADMIN_PASSWORD
      value: "admin"
    - name: KC_BOOTSTRAP_ADMIN_USERNAME
      value: "admin"
    - name: KC_BOOTSTRAP_ADMIN_PASSWORD
      value: "admin"
  extraContainerPorts:
    - name: debug
      containerPort: 5005
      protocol: TCP
  auth:
    adminUser: "admin"
    adminPassword: "admin"
  postgresql:
    enabled: false
  externalDatabase:
    annotations: {}
    database: keycloak
    existingSecret: ""
    existingSecretDatabaseKey: ""
    existingSecretHostKey: ""
    existingSecretPasswordKey: ""
    existingSecretPortKey: ""
    existingSecretUserKey: ""
    host: "local-authority-postgresql.local-authority.svc.cluster.local"
    password: keycloak
    port: 5432
    user: keycloak
  extraVolumes:
    - name: spi-volume
      emptyDir: {}
    - name: realm-volume
      emptyDir: {}
    - name: scripts-volume
      configMap:
        name: configmap-scripts
  extraVolumeMounts:
    - name: spi-volume
      mountPath: /opt/keycloak/providers
    - name: realm-volume
      mountPath: /opt/keycloak/data/import
    - name: scripts-volume
      mountPath: /scripts
    
  initContainers:
    - name: init-spi
      # Uncomment to allow running local builds of keycloak-authenticator, see /app-values/local/keycloak-authenticator/README.md
      #image: init-spi-local:latest
      imagePullPolicy: IfNotPresent
      image: curlimages/curl:8.16.0
      command: ["/bin/sh", "-c"]
      env:
        - name: ARTIFACT
          value: keycloak-authenticator
        - name: URL
          value: https://code.europa.eu/api/v4/projects/915/packages/maven/eu/europa/ec/simpl/keycloak-authenticator/2.7.0/keycloak-authenticator-2.7.0.jar
        - name: EIDAS_EXTENSION_ARTIFACT
          value: keycloak-eidas-demo-authenticator
        - name: EIDAS_EXTENSION_URL
          value: https://code.europa.eu/api/v4/projects/1313/packages/maven/eu/europa/ec/simpl/eidas-demo-keycloak-extension/0.4.0/eidas-demo-keycloak-extension-0.4.0.jar
      args:
        - |
          # Skip download if the keycloak-authenticator file already exists, to allow running local builds if needed
          if [ ! -f "/${ARTIFACT}.jar" ]; then
            curl -fSL -o /custom-spi/${ARTIFACT}.jar "${URL}";
          else
            echo "Skipping download: /${ARTIFACT}.jar is present, moving to /custom-spi";
            cp "/${ARTIFACT}.jar" "/custom-spi/${ARTIFACT}.jar"
          fi
          # Skip download if the keycloak-eidas-demo-authenticator file already exists, to allow running local builds if needed
          if [ ! -f "/${EIDAS_EXTENSION_ARTIFACT}.jar" ]; then
            curl -fSL -o /custom-spi/${EIDAS_EXTENSION_ARTIFACT}.jar "${EIDAS_EXTENSION_URL}";
          else
            echo "Skipping download: /${EIDAS_EXTENSION_ARTIFACT}.jar is present, moving to /custom-spi";
            cp "/${EIDAS_EXTENSION_ARTIFACT}.jar" "/custom-spi/${EIDAS_EXTENSION_ARTIFACT}.jar"
          fi
      volumeMounts:
        - name: spi-volume
          mountPath: /custom-spi
    - name: import-realms
      imagePullPolicy: IfNotPresent
      image: alpine:latest
      command: ["/bin/sh", "-c"]
      env:
        - name: REALMS_JSON
          value: |
            [
              {
                "name": "authority",
                "uri": "https://code.europa.eu/simpl/simpl-open/development/iaa/charts/-/raw/develop/samples/keycloak-realms/2.1.0/authority-realm-export.json?ref_type=heads",
                "redirectUris": "[ \"*\" ]"
              },
              {
                "name": "consumer",
                "uri": "https://code.europa.eu/simpl/simpl-open/development/iaa/charts/-/raw/develop/samples/keycloak-realms/2.1.0/participant-realm-export.json?ref_type=heads",
                "redirectUris": "[ \"*\" ]"
              }
            ]
      args:
        - |
          echo "Running my custom script"
          sh /scripts/import_and_fix.sh

      volumeMounts:
        - name: realm-volume
          mountPath: /config
        - name: scripts-volume
          mountPath: /scripts

vault:
  mode: dev
  server:
    #injector:
    #  enabled: false
    dev:
      enabled: true
    #standalone: false     # Disable standalone Raft mode to avoid persistence
    #dataStorage:
    #  enabled: false      # Disable PVC (no persistent volume)
    extraEnvironmentVars:
      VAULT_DEV_ROOT_TOKEN_ID: "root"     # Fixed root token for easy access
    readinessProbe:
      enabled: false
    resources:
      requests:
        cpu: 50m
        memory: 256Mi
      limits:
        cpu: 200m
        memory: 512Mi

redis:
  image:
    repository: bitnamilegacy/redis
  kubectl:
    image:
      repository: bitnamilegacy/kubectl
  security:
    allowInsecureImages: true
  architecture: standalone
  auth:
    enabled: true
    password: "admin"
  master:
    resources:
      requests:
        cpu: 30m
        memory: 64Mi
      limits:
        cpu: 100m
        memory: 128Mi
