hostFe: authority.fe.dev.simpl-europe.eu
cors:
  allowOrigin: https://authority.be.dev.simpl-europe.eu,https://authority.fe.dev.simpl-europe.eu,http://localhost:4202,http://localhost:4203,http://localhost:3000
ingress:
  issuer: dev-prod

env:
- name: API_URL
  value: "https://authority.be.dev.simpl-europe.eu"
- name: KEYCLOAK_URL
  value: "https://authority.be.dev.simpl-europe.eu/auth"
- name: KEYCLOAK_REALM
  value: "authority"
- name: KEYCLOAK_CLIENT_ID
  value: "frontend-cli"
  
microfrontends:
- name: sap
  application: sap
  path: "/sap"
- name: onboarding
  application: onboarding
  path: "/onboarding"
- name: usersroles
  application: usersandroles
  path: "/users-roles"
- name: participant
  application: participant-utility
  path: "/participant-utility"