apiVersion: batch/v1
kind: CronJob
metadata:
  name: update-chart-dependencies
spec:
  schedule: "*/1 * * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: update-chart-dependencies
            image: update-chart-dependencies:latest
            imagePullPolicy: IfNotPresent
            command: ["bash", "-c"]
            args:
              - |
                function update_chart() {
                  CHART_FILE="$1"
                  shift
                  HELM_FILTER="$*"
                  LOG_CONTEXT="$CHART_FILE" /app/update-chart-dependencies.bash \
                  --chart-file "$CHART_FILE" \
                  --path /tmp/p1 \
                  --git-url https://code.europa.eu/simpl/iaa/charts.git \
                  --git-credential "https://$GIT_USER:$GIT_PASSWORD@code.europa.eu" \
                  --git-branch feature/autoupdate-script-test \
                  --version-filter "$HELM_FILTER"
                }
                while read line; do
                  update_chart $line
                done << EOF
                /tmp/p1/app-values/ovh-dev-components/iaa-dsdev/authority/Chart.yaml .version | test("SNAPSHOT")
                /tmp/p1/app-values/ovh-dev-components/iaa-dsdev/consumer/Chart.yaml .version | test("SNAPSHOT")
                /tmp/p1/app-values/ovh-dev-components/iaa-dsdev/data-provider/Chart.yaml .version | test("SNAPSHOT")
                /tmp/p1/app-values/ovh-dev-components/iaa-dsstaging/authority/Chart.yaml .version | test("SNAPSHOT") | not
                /tmp/p1/app-values/ovh-dev-components/iaa-dsstaging/data-provider/Chart.yaml .version | test("SNAPSHOT") | not
                /tmp/p1/app-values/ovh-dev-components/iaa-dsstaging/consumer/Chart.yaml .version | test("SNAPSHOT") | not
                EOF

            envFrom:
            - secretRef:
                name: update-chart-dependencies-credentials
          restartPolicy: Never

---

apiVersion: v1
kind: Secret
metadata:
  name: update-chart-dependencies-credentials
type: Opaque
data:
  GIT_USER: "xxxxxxxxxxxx"
  GIT_PASSWORD: "xxxxxxxxxxxxxxxxxxxxxxxxxxxx"
  GIT_COMMITTER_NAME: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
  GIT_AUTHOR_NAME: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
  GIT_COMMITTER_EMAIL: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
  GIT_AUTHOR_EMAIL: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
