apiVersion: batch/v1
kind: CronJob
metadata:
  name: update-chart-dependencies
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: update-chart-dependencies
            image: update-chart-dependencies:latest
            imagePullPolicy: IfNotPresent
            command: ["bash", "-c"]
            args:
              - |
                /app/update-chart-dependencies.bash \
                --chart-file /tmp/p1/app-values/ovh-dev-components/iaads-1.0/participant-02/Chart.yaml \
                --path /tmp/p1 \
                --git-url https://code.europa.eu/simpl/iaa/charts.git \
                --git-credential "https://$GIT_USER:$GIT_PASSWORD@code.europa.eu" \
                --git-branch feature/autoupdate-script-test
            envFrom:
            - secretRef:
                name: update-chart-dependencies-credentials
          restartPolicy: Never

---

apiVersion: v1
kind: Secret
metadata:
  name: update-chart-dependencies-credentials
type: Opaque
data:
  GIT_USER: "xxxxxxxxxxxx"
  GIT_PASSWORD: "xxxxxxxxxxxxxxxxxxxxxxxxxxxx"
  GIT_COMMITTER_NAME: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
  GIT_AUTHOR_NAME: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
  GIT_COMMITTER_EMAIL: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
  GIT_AUTHOR_EMAIL: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
