hostFe: participant01-fe.dev.simpl-europe.eu
cors:
  allowOrigin: https://participant01-be.dev.simpl-europe.eu,https://participant01-fe.dev.simpl-europe.eu,http://localhost:4202,http://localhost:4203,http://localhost:3000
ingress:
  issuer: dev-prod

env:
- name: APPLICATION
  value: participant-utility
- name: API_URL
  value: "https://participant01-be.dev.simpl-europe.eu"
- name: KEYCLOAK_URL
  value: "https://participant01-be.dev.simpl-europe.eu/auth"
- name: KEYCLOAK_REALM
  value: "participant"
- name: KEYCLOAK_CLIENT_ID
  value: "frontend-cli"