apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: iaa-dstest-consumer
  namespace: argo-cd
  labels:
    owner: iaa
    scope: development
spec:
  project: iaa
  source:
    repoURL: https://code.europa.eu/simpl/simpl-open/development/iaa/charts.git
    targetRevision: feature/dev-agents
    path: app-values/ovh-dev-components/iaa-dstest/consumer
    helm:
      releaseName: iaa-dstest-consumer
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: iaa-dstest-consumer
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
  info:
  - name: Participant Type
    value: CONSUMER
