[tools]
java = "21"
"github:Pumahawk/klog" = "0.1.0"
mvnd = "1.0.3"
jq = "1.8.1"
docker-compose = "2.39.4"

[tasks."build:no-test"]
run = "mise run build -Dmaven.test.skip"

[tasks.dockerc]
run = "docker-cli-plugin-docker-compose -f .config/docker/docker-compose.yaml -p simpl-dev"

[tasks."dockerc:up"]
run = "mise r dockerc up -d"

[tasks."dockerc:stop"]
run = "mise r dockerc stop"

[tasks."db"]
run = "mise r dockerc ps db"

[tasks."db:up"]
run = "mise r dockerc:up db"

[tasks."db:stop"]
run = "mise r dockerc:stop db"

[tasks."db:prune"]
run = "mise r dockerc down db -v"

[tasks."db:connect"]
run = "mise run dockerc exec db psql --host localhost -U admin"

[env]
PROJECT_RELEASE_VERSION = "2.5.0-RC"

#Database
SIMPL_DB_PORT_FORWARD = "5432"

# Microservices
MICRO_PROFILES = "local,authority,local-authority"

MICRO_ONBOARDING_DB_URL = "jdbc:postgresql://localhost:5432/onboarding"
MICRO_ONBOARDING_DB_USERNAME = "onboarding"
MICRO_ONBOARDING_DB_PASSWORD = "onboarding"

MICRO_USERSROLES_DB_URL = "jdbc:postgresql://localhost:5432/usersroles"
MICRO_USERSROLES_DB_USERNAME = "usersroles"
MICRO_USERSROLES_DB_PASSWORD = "usersroles"

MICRO_SAP_DB_URL = "jdbc:postgresql://localhost:5432/securityattributesprovider"
MICRO_SAP_DB_USERNAME = "securityattributesprovider"
MICRO_SAP_DB_PASSWORD = "securityattributesprovider"

MICRO_AUTH_ISSUER_URI = "http://localhost:9010/auth/realms/authority"
MICRO_AUTH_SECKEY = "WTJNbjN4enZCYXViU0FzYUtNUHVzc0UyNkhWT3dYYlI2ZHBLZDZWQVliMD0="
MICRO_AUTH_DB_URL = "jdbc:postgresql://localhost:5432/authenticationprovider"
MICRO_AUTH_DB_USERNAME = "authenticationprovider"
MICRO_AUTH_DB_PASSWORD = "authenticationprovider"

MICRO_IDENTITY_DB_URL = "jdbc:postgresql://localhost:5432/identityprovider"
MICRO_IDENTITY_DB_USERNAME = "identityprovider"
MICRO_IDENTITY_DB_PASSWORD = "identityprovider"
MICRO_IDENTITY_EJBCA_KEYSTORE_LOCATION = "file:/home/lgandino/projects/simpl-certs/identity-provider/keystore.p12"
MICRO_IDENTITY_EJBCA_KEYSTORE_PASSWORD = "123-stella"
MICRO_IDENTITY_EJBCA_KEYSTORE_TYPE = "PKCS12"
MICRO_IDENTITY_EJBCA_TRUSTSTORE_LOCATION = "file:/home/lgandino/projects/simpl-certs/identity-provider/truststore.jks"
MICRO_IDENTITY_EJBCA_TRUSTSTORE_PASSWORD = "changeit"
MICRO_IDENTITY_EJBCA_TRUSTSTORE_TYPE = "JKS"

# MICRO_TIER1_GATEWAY_URL = "http://localhost:9010"
# MICRO_TIER1_REALM = "authority"
