[tools]
java = "21"
"github:Pumahawk/klog" = "0.1.0"
mvnd = "1.0.3"
jq = "1.8.1"
docker-compose = "2.39.4"

[tasks.dockerc]
run = "docker-cli-plugin-docker-compose -f .config/docker/docker-compose.yaml -p simpl-dev"

[tasks."dockerc:up"]
run = "mise r dockerc up -d"

[tasks."dockerc:stop"]
run = "mise r dockerc stop"

[tasks."db"]
run = "mise r dockerc ps db"

[tasks."db:up"]
run = "mise r dockerc:up db"

[tasks."db:stop"]
run = "mise r dockerc:stop db"

[tasks."db:prune"]
run = "mise r dockerc down db -v"

[tasks."db:connect"]
run = "mise run dockerc exec db psql --host localhost -U admin"

[env]
PROJECT_RELEASE_VERSION = "2.5.0-RC"

#Database
SIMPL_DB_PORT_FORWARD = "5432"

# Microservices
MICRO_ONBOARDING_DB_URL = "jdbc:postgresql://localhost:5432/onboarding"
MICRO_ONBOARDING_DB_USERNAME = "onboarding"
MICRO_ONBOARDING_DB_PASSWORD = "onboarding"

MICRO_USERSROLES_DB_URL = "jdbc:postgresql://localhost:5432/usersroles"
MICRO_USERSROLES_DB_USERNAME = "usersroles"
MICRO_USERSROLES_DB_PASSWORD = "usersroles"

MICRO_SAP_DB_URL = "jdbc:postgresql://localhost:5432/securityattributesprovider"
MICRO_SAP_DB_USERNAME = "securityattributesprovider"
MICRO_SAP_DB_PASSWORD = "securityattributesprovider"
