[tools]
java = "21"
mvnd = "1.0.3"
jq = "1.8.1"
docker-compose = "2.39.4"
kind = "0.30.0"
kubectl = "1.34.1"
docker-cli = "28.4.0"
helm = "3.19.0"
kubectx = "0.9.5"
kubens = "0.9.5"

[tasks.jqlog]
run = """
jq --unbuffered -r -R '. as $line | try (fromjson | "\\(.timestamp) \\(.micro // "") \\(.level) \\(.message) \\(."error.stack_trace" // "")") catch $line'
"""

[tasks."code:fmt"]
run = "mvnd -f simpl-repo spotless:apply"

[tasks."code:build"]
run = "mvnd clean install -fae -f simpl-repo/"

[tasks."code:build:no-test"]
run = "mise run code:build -Dlicense.skipDownloadLicenses -Dmaven.test.skip"

[tasks."code:test-automation:run-by-tag"]
run = "mvnd -f simpl-repo/test-automation resources:resources resources:testResources compiler:compile compiler:testCompile surefire:test -Dcucumber.filter.tags={{arg(name=\"tags\")}}"

[tasks."cluster:forward-node-compose"]
run = "docker-cli-plugin-docker-compose -f .config/docker/forward-node/docker-compose.yaml -p simpl-portforward"

[tasks."cluster:forward-node-up"]
run = "mise r cluster:forward-node-compose up -d"

[tasks."cluster:forward-node-down"]
run = "mise r cluster:forward-node-compose down -v"

[tasks."cluster:create"]
run = "kind create cluster --name simpl"

[tasks."cluster:destroy"]
run = "kind delete cluster --name simpl"

[tasks."cluster:start"]
run = "docker container start simpl-control-plane"

[tasks."cluster:status"]
run = "docker container ls -a --filter name=simpl-control-plane"

[tasks."cluster:stop"]
run = "docker container stop simpl-control-plane"

[tasks."cluster:bash"]
run = "docker exec -it simpl-control-plane bash"

[tasks."cluster:authority-install-or-upgrade"]
run = [
  """
  helm upgrade \
  -i \
  --dependency-update \
  --create-namespace \
  -n local-authority \
  local-authority \
  ./simpl-repo/charts/app-values/local/local-authority
  """,
 "kubens local-authority"
]

[tasks."cluster:authority-uninstall"]
run = "helm uninstall local-authority"

[tasks."zscaler:install-cluster"]
run = [
  "docker cp .config/certs/zscaler-ca.pem simpl-control-plane:usr/local/share/ca-certificates/zscaler-ca.crt",
  "docker exec simpl-control-plane update-ca-certificates",
]

[tasks."micro:run:authority-authenticationprovider".env]
SPRING_PROFILES_ACTIVE = "local-authority"
CRYPTO_SECRETKEYBASE64 = "KdSucCE6DSRFThqxv2frvx1h84HPFEy4ocEFwFDJC8A"
[tasks."micro:run:authority-authenticationprovider"]
run = "mvnd -f simpl-repo -pl :authenticationprovider spring-boot:run -Dspring-boot.run.jvmArguments=\"-Xms32m -Xmx64m -Djava.net.preferIPv4Stack=true\""

[tasks."micro:run:consumer-authenticationprovider".env]
SPRING_PROFILES_ACTIVE = "local-consumer"
CRYPTO_SECRETKEYBASE64 = "KdSucCE6DSRFThqxv2frvx1h84HPFEy4ocEFwFDJC8A"
[tasks."micro:run:consumer-authenticationprovider"]
run = "mvnd -f simpl-repo -pl :authenticationprovider spring-boot:run -Dspring-boot.run.jvmArguments=\"-Xms32m -Xmx64m -Djava.net.preferIPv4Stack=true\""

[tasks."micro:run:authority-identityprovider".env]
SPRING_PROFILES_ACTIVE = "local"
[tasks."micro:run:authority-identityprovider"]
run = "mvnd -f simpl-repo -pl :identity-provider spring-boot:run -Dspring-boot.run.jvmArguments=\"-Xms32m -Xmx64m\""

[tasks."micro:run:authority-onboarding".env]
SPRING_PROFILES_ACTIVE = "local"
[tasks."micro:run:authority-onboarding"]
run = "mvnd -f simpl-repo -pl :onboarding spring-boot:run -Dspring-boot.run.jvmArguments=\"-Xms32m -Xmx64m\""

[tasks."micro:run:authority-securityattributesprovider".env]
SPRING_PROFILES_ACTIVE = "local"
[tasks."micro:run:authority-securityattributesprovider"]
run = "mvnd -f simpl-repo -pl :security-attributes-provider spring-boot:run -Dspring-boot.run.jvmArguments=\"-Xms32m -Xmx64m\""

[tasks."micro:run:authority-tierone".env]
SPRING_PROFILES_ACTIVE = "local-authority"
[tasks."micro:run:authority-tierone"]
run = "mvnd -f simpl-repo -pl :tier1-gateway spring-boot:run -Dspring-boot.run.jvmArguments=\"-Xms32m -Xmx64m -Dio.netty.resolver.noPreferNative=true\""

[tasks."micro:run:consumer-tierone".env]
SPRING_PROFILES_ACTIVE = "local-consumer"
[tasks."micro:run:consumer-tierone"]
run = "mvnd -f simpl-repo -pl :tier1-gateway spring-boot:run -Dspring-boot.run.jvmArguments=\"-Xms32m -Xmx64m\""

[tasks."micro:run:authority-tiertwo".env]
SPRING_PROFILES_ACTIVE = "local-authority"
[tasks."micro:run:authority-tiertwo"]
run = "mvnd -f simpl-repo -pl :tier2-gateway spring-boot:run -Dspring-boot.run.jvmArguments=\"-Xms32m -Xmx64m\""

[tasks."micro:run:consumer-tiertwo".env]
SPRING_PROFILES_ACTIVE = "local-consumer"
[tasks."micro:run:consumer-tiertwo"]
run = "mvnd -f simpl-repo -pl :tier2-gateway spring-boot:run -Dspring-boot.run.jvmArguments=\"-Xms32m -Xmx64m\""

[tasks."micro:run:authority-usersroles".env]
SPRING_PROFILES_ACTIVE = "local-authority"
[tasks."micro:run:authority-usersroles"]
run = "mvnd -f simpl-repo -pl :usersroles spring-boot:run -Dspring-boot.run.jvmArguments=\"-Xms32m -Xmx64m\""

[tasks."micro:run:consumer-usersroles".env]
SPRING_PROFILES_ACTIVE = "local-consumer"
[tasks."micro:run:consumer-usersroles"]
run = "mvnd -f simpl-repo -pl :usersroles spring-boot:run -Dspring-boot.run.jvmArguments=\"-Xms32m -Xmx64m\""

[tasks."zscaler:install-jdk"]
run = "keytool -importcert -trustcacerts -alias zscaler-ca -file .config/certs/zscaler-ca.pem -keystore {{env.JAVA_HOME}}/lib/security/cacerts -storepass changeit -noprompt"

[tasks."zscaler:remove-jdk"]
run = "keytool -delete -alias zscaler-ca -keystore {{.envJAVA_HOME}}/lib/security/cacerts -storepass changeit"

[env]
PROJECT_RELEASE_VERSION = "2.5.0-RC"
KUBECONFIG = "./.config/.kube/config"

#Database
SIMPL_DB_PORT_FORWARD = "55432"
