apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: agent-service
build:
  artifacts:
    - image: agent-service
      context: simpl-repo/agent-service
      docker:
deploy:
  helm:
    releases:
      - name: agent-service
        version: v0.0.0
        chartPath: simpl-repo/agent-service/charts/
        setValues:
          global:
            profile: authority
            hostBe: participant.be.aruba-simpl.cloud
            hostTls: tls.authority.aruba-simpl.cloud
            keystore:
              password: "your-keystore-password"
          image:
            repository: agent-service
            tag: v0.0.0
            pullPolicy: IfNotPresent
          db:
            url: "jdbc:postgresql://postgresql.iaa.svc.cluster.local:5432/agentservice"
            username: "agentservice"
            password: "agentservice"
